---
- name: Enable nginx repo.
  template:
    src: "{{ nginx_package_name }}.repo.j2"
    dest: /etc/yum.repos.d/{{ nginx_package_name }}.repo
    owner: root
    group: root
    mode: 0644
  when: nginx_yum_repo_enabled

- name: Ensure nginx is installed.
  yum:
    name: "{{ nginx_package_name }}"
    state: installed
